version: "3.9"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_prod
    ports:
      - "8080:80"
    env_file:
      - .env.prod
    volumes:
      - ./wordpress:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_prod
    env_file:
      - .env.prod
    volumes:
      - db_data_prod:/var/lib/mysql

volumes:
  db_data_prod: